### PR TITLE
Cache bundler on CI

### PR DESCRIPTION
**Pull request by eapache**

### CODE REVIEW

**Comment by eapache** [comment]
Looks like it saves about 8 seconds, which is not nothing.

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious, bundler caching was available since December 17, 2014, but I see you just enabled it in this pull request (about a year later). Any reasons, please? 

Thanks.

**Comment by eapache** [comment]
I wasn't working on this repo regularly and I probably just didn't notice until then.

**Comment by Taher-Ghaleb** [comment]
I see. Thanks, @eapache, for your response.

**Pull request merged**
