### PR TITLE
never return nil from line_for_record, instead return an empty string…

### PR DESCRIPTION
**Pull request by Tikkoneus**
… if no other line can be found.

### CODE REVIEW

**Comment by Tikkoneus** [comment]
I was getting export exceptions for both ctags and cscope. Different exceptions for each, but both related to invalid methods on nil:NilClass. Returning an empty string made the resulting database usable by codequery. Is this a good approach?

**Comment by eapache** [comment]
I think I follow; if you could provide a small piece of code that fails this way when parsed and then exported, I'd appreciate being able to dig in a bit deeper.

**Comment by Tikkoneus** [comment]
When I threw starscope at a large directory of files (say, indexing my installed gems folder) I got tons of errors. Here are a few examples:
- syntaxerror: Invalid character (javascript)
- unterminated string meets end of file (ruby)
- undefined method `x' for obj:Class

One specific error I found really entertaining was that in Ruby any case of [__ENCODING__](https://ruby-doc.org/core-2.5.3/Encoding.html) produces a Parser::Source::Map that doesn't respond to .name but responds to .type with :const rather than actually being a Parser::Source::Map::Constant. I think it must be because the parser considers it a "keyword", i.e. expression, but the ast resolves it into the actual encoding constant? Not sure. Anyway if you run starscope on a ruby file containing only "puts __ENCODING__" you'll get an error.

But all of those are merely symptoms. The real underlying issue is that:
- many types of parse errors can and do happen in the file extractor
- this [rescue](https://github.com/eapache/starscope/blob/master/lib/starscope/db.rb#L282) in db.rb:extract_file doesn't do any transactional rollbacks. i.e. as the function goes records are created in a partially-valid state and those records aren't complete until the function completes successfully ... but any error raised at any point during extraction leaves the partially-valid record and meta for that record.

The result is that when db.rb:line_for_record is called by the exporters it's quite possible for both conditional returns to fail. The block will end up returning nil which causes a variety of fun backtraces over in the exporter.

I figured returning an empty line was a reasonable and expedient way to silently ignore parse errors and allow the exporters to complete.

**Comment by Tikkoneus** [comment]
Travis seems to be complaining about single- vs double-quoted strings. If you accept this pull request I can fix it to be single-quoted before you pull.

**Comment by eapache** [comment]
> as the function goes records are created in a partially-valid state and those records aren't complete until the function completes successfully ... but any error raised at any point during extraction leaves the partially-valid record and meta for that record.

This doesn't match my understanding. The various extractors add records in a transactional way by calling `yield`. Either they call yield or they don't; there's no way for them to yield a partial record?

:thinking:

Oh, are you referring to the fact that if a record is yielded, and then the extractor throws, that `@meta[:files][file][:lines] = lines` never runs? That seems like it might be causing this? I think the better fix for that might just be moving the last 5 lines of `extract_file` to an ensure so that the metadata is correctly populated even if the extraction failed?

**Comment by Tikkoneus** [comment]
Oh, I see, I wasn't correctly following the flow. You're saying if we add the ensure at the end of extract_file then any record for which line_for_record might be called is guaranteed to have a valid non-nil entry in file[:lines] because the record is only created by the yield statement and by the time yield is called we know the extractor hasn't thrown an exception? I agree `ensure` is a better approach.

Out of curiosity is it absolutely impossible for a record to exist but have no line number? If such a record existed then the file[:lines] check in line_for_record would be true but the line itself might still be nil.

**Comment by eapache** [comment]
Ya, exactly.

> Out of curiosity is it absolutely impossible for a record to exist but have no line number? If such a record existed then the file[:lines] check in line_for_record would be true but the line itself might still be nil.

It's not principally impossible, but it is currently true that every record yielded by the extractors I built does have a line number. You could have an extractor that yielded line-less records, and it would mostly work but wouldn't be exportable to ctags/cscope. The correct fix to support something like this would probably be to skip cases in the exporter when `line_for_record` returns nil since we don't have enough information to export correctly in that case anyway.

**Comment by Tikkoneus** [comment]
Yeah, thanks for the explanation. I have a much better understanding of how starscope works after digging into your response.

I reproduced the exception I was getting and confirmed that it was because the record had been inserted into the tbl but the parse exception had caused file[:lines] not to be populated, exactly as you suspected. Adding the `ensure` did, indeed, fix it.

**Comment by eapache** [comment]
You can update this PR (or file a new one) for the ensure fix, or I'll get around to it probably this weekend.

**Comment by Tikkoneus** [comment]
Yes, apologies, I didn't get time yesterday. Looks better now? (Please pardon my inexperience with git!)

**Comment by eapache** [comment]
Thank you!

**Pull request merged**
